### ISSUE TITLE
Stuck at 1% Preview Post

### ISSUE THREAD

**Issue by crocofied** [johnwarne/upvote-rss#11]
Hello,

installed the application with portainer and behind cloudflare tunnel. Thats my compose:
```yml
version: '3'
services:
  upvote-rss:
    image: ghcr.io/johnwarne/upvote-rss:latest
    container_name: upvote-rss
    environment:
      - REDDIT_USER=***
      - REDDIT_CLIENT_ID=***
      - REDDIT_CLIENT_SECRET=***
      - REDIS_HOST=http://localhost
      - REDIS_PORT=3014
    volumes:
      - cache:/app/cache
    ports:
      - "3013:80"
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "3014:6379"
    restart: unless-stopped

volumes:
  cache:
```

But i am stuck at 1%

![Image](https://github.com/user-attachments/assets/d803789b-86f2-4f06-a90d-9a1b8399db0d)

Browser Console Logs:
`Uncaught (in promise) SyntaxError: Unexpected token '<', "<br />
<b>"... is not valid JSON`

Docker Logs:
```
WRN | ts=1739661453.4897187 logger=admin msg=admin endpoint disabled 
WRN | ts=1739661453.4907992 logger=http.auto_https msg=server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server server_name=php http_port=80 
INF | ts=1739661453.4913948 logger=tls.cache.maintenance msg=started background certificate maintenance cache=0xc000036f80 
INF | ts=1739661453.5886283 msg=FrankenPHP started 🐘 php_version=8.4.3 num_threads=8 
WRN | ts=1739661453.589358 logger=http msg=HTTP/2 skipped because it requires TLS network=tcp addr=:80 
WRN | ts=1739661453.5894012 logger=http msg=HTTP/3 skipped because it requires TLS network=tcp addr=:80 
INF | ts=1739661453.5894141 logger=http.log msg=server running name=php protocols=["h1","h2","h3"] 
INF | ts=1739661453.5894513 msg=Caddy serving PHP app on :80 
INF | ts=1739661453.611382 logger=tls msg=cleaning storage unit storage=FileStorage:/data/caddy 
INF | ts=1739661453.6175601 logger=tls msg=finished cleaning storage units 
```

**Comment by johnwarne** [comment]
I'm in the middle of adding some better logging and error outputs to the app. In the meantime, can you try changing your `REDIS_HOST` env variable to `http://redis` (the name of the Redis container in your stack)?

**Comment by AtHeartEngineer** [comment]
Even without using redis I am getting the same bug

**Comment by johnwarne** [comment]
Ok this new message in the console is about not being able to fetch an API response from a platform. Can you paste the URL from your browser, omitting your IP/domain?

**Comment by crocofied** [comment]
Yes @AtHeartEngineer , I just added redis bc I thought it may fix the bug bc i also had it without redis.

@johnwarne Wdym? It is for every subreddit and HackerNews i have tried. Do you need the domain of my UpvoteRSS instance?

**Comment by AtHeartEngineer** [comment]
> Ok this new message in the console is about not being able to fetch an API response from a platform. Can you paste the URL from your browser, omitting your IP/domain?

<img width="1690" alt="Image" src="https://github.com/user-attachments/assets/0684a2df-d163-4c31-96d0-6deff71fce1f" />

`/js/script.js:350`

<img width="1331" alt="Image" src="https://github.com/user-attachments/assets/5623b428-4ee4-457e-9ff0-d2beff44c517" />

 this gets called over and over for ycombinator, the response for all of them is `{
	"progress": 1
}`

The backend isn't giving much info

**Comment by johnwarne** [comment]
@AtHeartEngineer Can you paste the contents of your docker compose file here? And try opening in a new private window with no browser extensions loaded and click the `Refresh cache` button in the right column.

**Comment by AtHeartEngineer** [comment]
@johnwarne I figured it out, the cache folder wasn't writable. The container is running as root and the cache folder was owned by root but for some reason it didn't have permissions to write into it?? idk, I `chmod 777`ed it and now its working, so I'll tailer back permissions and make a user for it and own the dir.

<img width="1800" alt="Image" src="https://github.com/user-attachments/assets/75ca549c-8e84-419c-b68a-2d6346962872" /> Same result in a private window on chrome and firefox.

```
services:
  upvote-rss:
    image: ghcr.io/johnwarne/upvote-rss:latest
    container_name: upvote-rss
    environment:
      - REDDIT_USER=myusername
      - REDDIT_CLIENT_ID="clientid"
      - REDDIT_CLIENT_SECRET=""
      - OLLAMA_URL="ip:port"
      - OLLAMA_MODEL="llama3.1"
    volumes:
      - ./cache:/app/cache
    ports:
      - "8675:80"
    restart: unless-stopped
```
